PlotSoft Project Group 1 - Ink Dispensing Control
iis-powp-2018/powp_plotsoft_project pull request #3
Opened 2018-05-31 18:20 UTC by ganymede95

Artur Sonenberg 195060
Bartłomiej Chmielarz 202128 
Bartłomej Werner 202327

2018-06-02 11:23 UTC, kowallus requested changes
Required updates are marked using 'FIX TO MERGE:' prefix.  In case of repeated issues usually only one place is marked, but fixes are expected to be made to similar places.
Other comments are simply feedback informations and suggestions (for achiving better mark).

For more suggestions and guidance ask in comments, ask during next classes or come to office hours.

Sorry, I DO NOT allow you to prepare presentation before submitting fixes.

2018-06-02 11:23 UTC, kowallus commented on src/main/java/edu/iis/powp/inkDriver/CommandEditor.java
> +    private ArrayList<IPlotterCommand> commandList = new ArrayList<>();
No seperation between GUI and logic (big class).

2018-06-02 11:23 UTC, kowallus commented on src/main/java/edu/iis/powp/inkDriver/CommandEditor.java
> +public class CommandEditor extends JFrame implements WindowComponent {
Feature weakly related to the topic. Good for testing, but does not introduce any patterns or interesting design.

2018-06-02 11:23 UTC, kowallus commented on src/test/java/edu/iis/powp/gui/TestPlotterApp.java
> +		InkGui inkGui = InkGui.getInstance();
FIX TO MERGE: Great deal of this code can be moved outside TestPlotterApp (only called within). 
The goal is to seperate responsibilites and make merging for other groups easier.

2018-06-02 11:23 UTC, kowallus commented on src/main/java/edu/iis/powp/inkDriver/InkGui.java
> +public class InkGui extends JFrame implements WindowComponent{
Lack of seperation between GUI and logic. Class, hard to understand.

2018-06-02 11:23 UTC, kowallus commented on src/test/java/edu/iis/powp/gui/TestPlotterApp.java
> +	private final static float initialInkLvl = 400f;
FIX TO MERGE: CONSTANTS UPPERCASE

2018-06-02 11:23 UTC, kowallus commented on src/test/java/edu/iis/powp/gui/TestPlotterApp.java
> +		plotter = new InkController(plotter, initialInkLvl);
Hardwired functionality. The goal was to make it optional. If new driver will be added it cannot be automatically equipped with InkController decorator. It should be possible using observer pattern implemented in DriverManager.

2018-06-02 11:23 UTC, kowallus commented on src/test/java/edu/iis/powp/events/SelectLoadSecretCommandOptionListener.java
> +		commands.add(new DrawToCommand(-50, 100));
FIX TO MERGE: Unnecessary change. Please revert!

2018-06-02 11:23 UTC, kowallus commented on src/main/java/edu/iis/powp/inkDriver/InkController.java
> +    private InkGui inkGui = InkGui.getInstance();
FIX TO MERGE: Direct dependency to GUI class

2018-06-02 11:23 UTC, kowallus commented on src/main/java/edu/iis/powp/inkDriver/InkGui.java
> +        inkGuiUpdater.updateValue(500);
Hardcoded value, but not a constant? 
It would be better to add possibility to input the value than to develop CommandEditor.

2018-06-02 11:23 UTC, kowallus commented on src/main/java/edu/iis/powp/inkDriver/InkController.java
> +    public boolean isEnoughInk(int x, int y){
FIX TO MERGE: Many responsibilities mixed in a method. Name of the method suggest only querying. Pop ups and updates not excpected.

2018-06-02 11:23 UTC, kowallus commented on src/main/java/edu/iis/powp/inkDriver/InkController.java
> +    public void drawWithCriticalCharge(int x, int y){
This is a responsibility of InkControllerWithCriticalCharge class.

2018-06-02 11:23 UTC, kowallus commented on src/main/java/edu/iis/powp/inkDriver/InkController.java
> +            inkGui.informationPopUp();
FIX TO MERGE: This action does not belong here. To decouple it, an observer pattern could be applied to add appropriate functionality in case of an event specified in the condition.

2018-06-07 12:51 UTC, ganymede95 commented on src/test/java/edu/iis/powp/gui/TestPlotterApp.java
> +	private final static float initialInkLvl = 400f;
Fixed

2018-06-07 12:52 UTC, ganymede95 commented on src/test/java/edu/iis/powp/events/SelectLoadSecretCommandOptionListener.java
> +		commands.add(new DrawToCommand(-50, 100));
Fixed

2018-06-09 11:37 UTC, bartwe2 commented on src/test/java/edu/iis/powp/gui/TestPlotterApp.java
> +		InkGui inkGui = InkGui.getInstance();
Fixed

2018-06-09 11:37 UTC, bartwe2 commented on src/main/java/edu/iis/powp/inkDriver/InkGui.java
> +public class InkGui extends JFrame implements WindowComponent{
Fixed

2018-06-09 11:39 UTC, bartwe2 commented on src/test/java/edu/iis/powp/gui/TestPlotterApp.java
> +		plotter = new InkController(plotter, initialInkLvl);
Fixed
Plotter is automatically decorated, we will add switch in GUI for enable critical charge.

2018-06-09 11:39 UTC, bartwe2 commented on src/main/java/edu/iis/powp/inkDriver/InkController.java
> +    private InkGui inkGui = InkGui.getInstance();
Fixed

2018-06-10 18:17 UTC, ganymede95 commented on src/main/java/edu/iis/powp/inkDriver/InkGui.java
> +        inkGuiUpdater.updateValue(500);
Fixed: now the value is changed dynamically in the UI

2018-06-15 10:02 UTC, DKaito commented
@kowallus Probably everything is done and we are ready to merge.

2018-06-15 12:20 UTC, kowallus requested changes
Well done! Still, some minor issues require fixing. 

I ALLOW you to prepare a presentation before making fixes and merging.

2018-06-15 12:20 UTC, kowallus commented on src/main/java/edu/iis/powp/inkDriver/InkController.java
> +    public boolean isEnoughInk(int x, int y){
FIX TO MERGE: Still not fixed! (method name or logic)

2018-06-15 12:20 UTC, kowallus commented on src/main/java/edu/iis/powp/inkDriver/InkGuiLogic.java
> +        if(!(application.getDriverManager().getCurrentPlotter() instanceof  InkController || application.getDriverManager().getCurrentPlotter() instanceof InkControllerWithCriticalCharge))
FIX TO MERGE: extract method to make the condition clear. (CLEAN CODE)

2018-06-15 12:20 UTC, kowallus commented on src/main/java/edu/iis/powp/inkDriver/InkGuiObserver.java
> +        guiLogic.injectInkControl();
FIX TO MERGE: Make injecting ink control optional (e.g., checkbox in GUI).

2018-06-20 07:44 UTC, kowallus approved these changes
OK. 
Note: There exist some minor bugs concerning changing a driver (observer implementation and ink controller GUI refresh.

2018-06-20 07:44 UTC, kowallus commented on src/main/java/edu/iis/powp/inkDriver/InkGuiLogic.java
> +        if(!(plotter instanceof InkController || plotter instanceof InkControllerWithCriticalCharge))
I meant extracting the condition: if (!isDecorated(plotter)) but it also ok.

2018-06-20 07:44 UTC, merged