Projekt zadanie C edytor
iis-powp-2018/powp_plotsoft_project pull request #5
Opened 2018-05-31 20:32 UTC by adinowi

2018-06-02 11:30 UTC, kowallus requested changes
Required updates are marked using 'FIX TO MERGE:' prefix.  In case of repeated issues usually only one place is marked, but fixes are expected to be made to similar places.
Other comments are simply feedback informations and suggestions (for achiving better mark).

For more suggestions and guidance ask in comments, ask during next classes or come to office hours.

Sorry, I DO NOT allow you to prepare presentation before submitting fixes.

2018-06-02 11:30 UTC, kowallus commented on src/main/java/edu/iis/powp/command/factory/SimpleCommandFactory.java
> +			while(i.hasNext()) {
This is O(n)! For the sake of efficiency HashMap should be used.

2018-06-02 11:30 UTC, kowallus commented on src/main/java/edu/iis/powp/command/factory/SimpleCommandFactory.java
> +	public abstract IPlotterCommand makeSimpleCommand(Coordinates coordinates);
Method not used in a polimorphic manner. Not a case for an abstract factory. Only checkPool code reuse.

2018-06-02 11:30 UTC, kowallus commented on src/test/java/edu/iis/powp/gui/GUI.java
> +  public static void main(String[] args) {
FIX TO MERGE: Does it work? I got errors.

2018-06-02 11:30 UTC, kowallus commented on src/main/java/edu/iis/powp/command/gui/CommandEditWindow.java
> +					// not implemented yet
FIX TO MERGE: Too bad.

2018-06-02 11:30 UTC, kowallus commented on src/main/java/edu/iis/powp/command/complex/ComplexCommandBuilder.java
> +public class ComplexCommandBuilder {
FIX TO MERGE: Code not working!

2018-06-02 11:30 UTC, kowallus commented on src/main/java/edu/iis/powp/command/complex/ComplexCommand.java
> +public class ComplexCommand implements ICompoundCommand, ICompoundCommandEditor {
FIX TO MERGE: Please create intermediate package for your functionality (e.g. package edu.iis.powp.command.editor....)

2018-06-02 11:30 UTC, kowallus commented on src/main/java/edu/iis/powp/command/complex/ICompoundCommandEditor.java
> +public interface ICompoundCommandEditor {
You should use interface instead of ComplexCommand whereever possible.

2018-06-02 11:30 UTC, kowallus commented on src/main/java/edu/iis/powp/command/gui/CommandEditWindow.java
> +				ComplexCommand currentCommand = (ComplexCommand) commandManager.getCurrentCommand();
Ugly cast.
Is tangling to ComplexCommand necessary?

2018-06-02 11:30 UTC, kowallus commented on src/main/java/edu/iis/powp/command/gui/CommandEditWindow.java
> +			public void actionPerformed(ActionEvent e) {
FIX TO MERGE: Lack of seperation between GUI and logic. Big class, hard to understand.

2018-06-02 11:30 UTC, kowallus commented on src/main/java/edu/iis/powp/command/manager/PlotterCommandManager.java
> +		setCurrentCommand(new ComplexCommand(commandList));
FIX TO MERGE: Unacceptable change. Other groups may want to make similar "hack". I cannot allow it. You cannot enforce here an implementation. This has to be implemented differently. 
You MUST be open to different implementations of ICompoundCommand passed using void setCurrentCommand(IPlotterCommand).

2018-06-02 11:30 UTC, kowallus commented on src/main/java/edu/iis/powp/command/gui/CommandEditWindow.java
> +					currentCommand.changeSequence(selectedIndex, selectedIndex + 1);
Mutating current command without using setCurrentCommand would make other functionalities unaware of the change.

2018-06-02 11:30 UTC, kowallus commented on src/main/java/edu/iis/powp/command/SetPositionCommand.java
> +public class SetPositionCommand extends SimpleCommand {
FIX TO MERGE: A serious change to IPlotterCommand hierarchy (may interfere with other groups). I need an explaination that convince me that it is fairly necessary. Yet, I am afraid that it is a case of 'form over content'

2018-06-06 19:32 UTC, SwiderskaA commented on src/test/java/edu/iis/powp/gui/GUI.java
> +  public static void main(String[] args) {
This class were done only for internal test purposes. I moved the logic to the final app. I didn't forget to remove this file

2018-06-07 07:42 UTC, kowallus commented on src/test/java/edu/iis/powp/gui/GUI.java
> +  public static void main(String[] args) {
OK. I understand that you did forget (rather than "didn't forget"). Please remove unnecessary sources.

2018-06-14 17:38 UTC, SwiderskaA commented on src/main/java/edu/iis/powp/command/gui/CommandEditWindow.java
> +					// not implemented yet
I removed method and button from UI as business logic were not implemented. Only UI stub were done

2018-06-14 17:58 UTC, SwiderskaA commented on src/main/java/edu/iis/powp/command/gui/CommandEditWindow.java
> +			public void actionPerformed(ActionEvent e) {
Class refactored. Added Inner Class for ActionListeners. Cleanup in constructor. Add small private method to separate logic into simple clear methods

2018-06-14 20:51 UTC, SwiderskaA commented on src/main/java/edu/iis/powp/command/manager/PlotterCommandManager.java
> +		setCurrentCommand(new ComplexCommand(commandList));
Method changed to handle ICoumpoundCommand interface.

2018-06-14 21:17 UTC, SwiderskaA commented on src/main/java/edu/iis/powp/command/complex/ComplexCommandBuilder.java
> +public class ComplexCommandBuilder {
Builder removed

2018-06-14 21:19 UTC, SwiderskaA commented on src/main/java/edu/iis/powp/command/complex/ComplexCommand.java
> +public class ComplexCommand implements ICompoundCommand, ICompoundCommandEditor {
It's special package complex in command package. There are only 2 items (class & interfejs).

2018-06-14 21:21 UTC, SwiderskaA commented on src/main/java/edu/iis/powp/command/complex/ICompoundCommandEditor.java
> +public interface ICompoundCommandEditor {
Fixed in most places. Used ICompundCommand interface whenever where possible

2018-06-14 21:22 UTC, SwiderskaA commented on src/main/java/edu/iis/powp/command/gui/CommandEditWindow.java
> +				ComplexCommand currentCommand = (ComplexCommand) commandManager.getCurrentCommand();
Cast removed. There is CompoundCommand interface used.

2018-06-14 21:28 UTC, SwiderskaA commented on src/main/java/edu/iis/powp/command/SetPositionCommand.java
> +public class SetPositionCommand extends SimpleCommand {
the SimpleCommand implements IPlotterCommand so in hierarchy SetPositionCommand  is still 'IPlotterCommand'

2018-06-15 17:01 UTC, adinowi commented
I think we fixed everything and we can merge it

2018-06-16 09:00 UTC, kowallus requested changes
Almost done! Still, some minor issues require fixing. 

I ALLOW you to prepare a presentation before making fixes and merging.

2018-06-16 09:00 UTC, kowallus commented on src/main/java/edu/iis/powp/command/factory/IPlotterCommandFactory.java
> +public class IPlotterCommandFactory {
PlotterCommandFactory would be better (this factory is not an interface)

2018-06-16 09:00 UTC, kowallus commented on src/main/java/edu/iis/powp/command/factory/IPlotterCommandFactory.java
> +	 * @param coordinates Coordinates to check
Obsolete javadoc (coordinates->commandId)

2018-06-16 09:00 UTC, kowallus commented on src/main/java/edu/iis/powp/command/gui/CommandEditWindow.java
>  	private DefaultListModel model;
The declared type could be AbstractListModel.
GUI is still not definitely separated from the logic (all in one file). Is it possible that extracting logic to other class and sharing the model would make it possible?

2018-06-16 09:00 UTC, kowallus commented on src/test/java/edu/iis/powp/events/SelectLoadSecretCommandOptionListener.java
> +		ComplexCommand complexCommand = new ComplexCommand(commands);
FIX TO MERGE: Application (in general) should still rely on ICompoundCommand. Such modifications are not allowed. Others groups can introduce their own implementations of ComplexCommand and must have similar restrictions!

2018-06-16 09:06 UTC, kowallus submitted a review, later dismissed
FIX TO MERGE: Revert SelectLoadSecretCommandOptionListener to master.
FIX TO MERGE: Loading a command in plotterCommandManager makes edited command "disconnected" from the application. You can either make appropriate reaction by attaching an observer to commandManager or by adding a button which would load edited command to commandManager.

2018-06-29 10:50 UTC, adinowi commented
I fixed everything

2018-06-29 12:18 UTC, kowallus commented
Almost merged, so I give you 4.5 for project.

2018-06-29 12:18 UTC, closed without merging