IO1 gr.A InkController
iis-powp-2018/powp_plotsoft_project pull request #6
Opened 2018-06-04 16:39 UTC by goczalk

Klaudia Goczał 195172
Mayyar Karkout 204641
Monika Jędrzejek

2018-06-05 11:44 UTC, kowallus requested changes
Required updates are marked using 'FIX TO MERGE:' prefix. In case of repeated issues usually only one place is marked, but fixes are expected to be made to similar places.

Other comments are simply feedback informations and suggestions (for achiving better mark).

For more suggestions and guidance ask in comments, ask during next classes or come to office hours.

Sorry, I DO NOT allow you to prepare presentation before submitting fixes.

2018-06-05 11:44 UTC, kowallus commented on src/main/java/edu/iis/powp/controllers/ink/SimmulationInkController.java
> +    private float MAX_LEVEL_INK = 1000;
FIX TO MERGE: If it is a constant declare it final static

2018-06-05 11:44 UTC, kowallus commented on src/main/java/edu/iis/powp/controllers/ink/SimmulationInkController.java
> +        addObservator(new InkInformer());
FIX TO MERGE: Dependency between observable and observer. SimmulationInkController should not be aware of InkInformer (configure observer externally).

2018-06-05 11:44 UTC, kowallus commented on src/test/java/edu/iis/powp/controllers/ink/EnoughInkForMultiplyLinesTest.java
> +        System.out.println("Ink level: " + inkController.getInkLevel());
Are these cases not suitable for using junit framework and assert expected values?

2018-06-05 11:44 UTC, kowallus commented on src/test/java/edu/iis/powp/gui/TestPlotterApp.java
> +	private static void setupInkControllerMenu(Application application) {
FIX TO MERGE: This code can be moved outside TestPlotterApp (only called within). 

The goal is to seperate responsibilites and make merging for other groups easier.

2018-06-05 11:44 UTC, kowallus commented on src/main/java/edu/iis/powp/controllers/ink/SimmulationInkController.java
> +    public boolean checkInkIsEnough(float level) {
The name of the method does not suggest issueing notification. 
Does this method really need to return boolean and call observers?
Is it really necessary to mix these responsibilities or maybe e.g. notifyIfNotEnough would be enough?

2018-06-05 11:44 UTC, kowallus commented on src/main/java/edu/iis/powp/controllers/ink/InkInformer.java
> +        Logger.getLogger(Logger.GLOBAL_LOGGER_NAME).log(WARNING, "Ink Level on too low level, impossible to draw." +
Why "Ink Level on too low level, impossible to draw."  is fixed? Shows even if called from the main menu and full cardiridge.

2018-06-05 11:44 UTC, kowallus commented on src/main/java/edu/iis/powp/adapter/LineAdapterPlotterDriver.java
> +		this.inkController = SimmulationInkController.getInstance();
FIX TO MERGE: Hardwired functionality. The goal was to make it optional. If new driver will be added it cannot be automatically equipped with InkController. It would be possible if it has been implemented e.g. as a decorator. 
It should be possible to attach such decorator using observer pattern implemented in DriverManager.

2018-06-05 13:31 UTC, goczalk commented on src/main/java/edu/iis/powp/controllers/ink/SimmulationInkController.java
> +    private float MAX_LEVEL_INK = 1000;
@mjakmiyo

2018-06-05 13:32 UTC, goczalk commented on src/main/java/edu/iis/powp/controllers/ink/InkInformer.java
> +        Logger.getLogger(Logger.GLOBAL_LOGGER_NAME).log(WARNING, "Ink Level on too low level, impossible to draw." +
@MeringueMayar

2018-06-19 21:52 UTC, goczalk commented
All sugestions applied. Sorry for delay.

2018-06-20 07:48 UTC, kowallus requested changes
COMPILE ERROR: I cannot check or merge.

2018-06-20 07:48 UTC, kowallus commented on src/test/java/edu/iis/powp/gui/TestPlotterApp.java
> +cc428dcb40ab5420b7357110551afb38959ff72f
Cannot compile!

2018-06-21 08:52 UTC, kowallus requested changes
Almost done, but merging still impossible.

You can make presentation today.

2018-06-21 08:52 UTC, kowallus commented on src/test/java/edu/iis/powp/controllers/ink/InkControllerTest.java
> +import org.junit.Before;
FIX TO MERGE: Dependency to junit not added to pom.xml

2018-06-21 08:52 UTC, kowallus commented on src/main/java/edu/iis/powp/controllers/ink/LinePlotterInkControlDriver.java
> +    private SimmulationInkController inkController;
Why direct coupling with SimmulationInkController when there is an interface InkControllerInterface?

2018-06-21 08:52 UTC, kowallus commented on src/test/java/edu/iis/powp/gui/TestPlotterApp.java
> +		IPlotter plotter = new LinePlotterInkControlDriver(linePlotter);
FIX TO MERGE: Still, this functionality is not optional (hardwired). If a new driver will be added it cannot be automatically equipped with InkController. It should be possible to attach LinePlotterInkControlDriver using observer pattern implemented in DriverManager. There should be also an option to TURN OFF ink control (it is hard to use this feature at all). When the application starts the decorator could be attached in a separate setupInkController method.

2018-06-25 23:43 UTC, goczalk commented
Może teraz? ;) 

Przy okazji akcent humorystyczny, stworzony podczas pracowania nad innym projektem, ale tutaj też pasujący...

![img_7226](https://user-images.githubusercontent.com/17785919/41881162-515bd768-78e2-11e8-9833-7aa7f60d46f1.JPG)
![image 2](https://user-images.githubusercontent.com/17785919/41881163-517b049e-78e2-11e8-8e7f-1724397b0918.png)

2018-06-27 20:30 UTC, kowallus approved these changes

2018-06-27 20:31 UTC, kowallus commented
You have two fails in unit tests, but I will merge ;)

2018-06-27 20:31 UTC, merged